"""Add all Star Wars tables and favorites 2

Revision ID: eea8720bcd61
Revises: 5e02c6a3d483
Create Date: 2025-04-20 16:32:00.651751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eea8720bcd61'
down_revision = '5e02c6a3d483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
